name: Platform Engineering CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-ci:
    name: Validar Módulo Terraform
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout del código
        uses: actions/checkout@v4

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: 🧹 Validación de Formato (fmt)
        run: terraform fmt -check -recursive
        
      - name: 🏗️ Terraform Init
        run: terraform init -backend=false
        working-directory: ./examples/basic-s3

      - name: ✅ Validación de Sintaxis (validate)
        run: terraform validate
        working-directory: ./examples/basic-s3

      - name: 🛡️ Análisis Estático de Seguridad (Checkov)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          quiet: true